# Generated by Django 2.2.5 on 2019-10-01 04:39

from django.db import migrations, models
import pocketmovie.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextBigramKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(pocketmovie.enums.Genre('action'), 'action'), (pocketmovie.enums.Genre('romance'), 'romance'), (pocketmovie.enums.Genre('horror'), 'horror')], max_length=20)),
                ('gram_1', models.CharField(choices=[(pocketmovie.enums.SentenceContext('description'), 'description'), (pocketmovie.enums.SentenceContext('dialogue'), 'dialogue'), (pocketmovie.enums.SentenceContext('direction'), 'direction'), (pocketmovie.enums.SentenceContext('actor_name'), 'actor_name')], max_length=20)),
                ('gram_2', models.CharField(choices=[(pocketmovie.enums.SentenceContext('description'), 'description'), (pocketmovie.enums.SentenceContext('dialogue'), 'dialogue'), (pocketmovie.enums.SentenceContext('direction'), 'direction'), (pocketmovie.enums.SentenceContext('actor_name'), 'actor_name')], max_length=20)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContextTrigramKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(pocketmovie.enums.Genre('action'), 'action'), (pocketmovie.enums.Genre('romance'), 'romance'), (pocketmovie.enums.Genre('horror'), 'horror')], max_length=20)),
                ('gram_1', models.CharField(choices=[(pocketmovie.enums.SentenceContext('description'), 'description'), (pocketmovie.enums.SentenceContext('dialogue'), 'dialogue'), (pocketmovie.enums.SentenceContext('direction'), 'direction'), (pocketmovie.enums.SentenceContext('actor_name'), 'actor_name')], max_length=20)),
                ('gram_2', models.CharField(choices=[(pocketmovie.enums.SentenceContext('description'), 'description'), (pocketmovie.enums.SentenceContext('dialogue'), 'dialogue'), (pocketmovie.enums.SentenceContext('direction'), 'direction'), (pocketmovie.enums.SentenceContext('actor_name'), 'actor_name')], max_length=20)),
                ('gram_3', models.CharField(choices=[(pocketmovie.enums.SentenceContext('description'), 'description'), (pocketmovie.enums.SentenceContext('dialogue'), 'dialogue'), (pocketmovie.enums.SentenceContext('direction'), 'direction'), (pocketmovie.enums.SentenceContext('actor_name'), 'actor_name')], max_length=20)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContextUnigramKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(pocketmovie.enums.Genre('action'), 'action'), (pocketmovie.enums.Genre('romance'), 'romance'), (pocketmovie.enums.Genre('horror'), 'horror')], max_length=20)),
                ('gram_1', models.CharField(choices=[(pocketmovie.enums.SentenceContext('description'), 'description'), (pocketmovie.enums.SentenceContext('dialogue'), 'dialogue'), (pocketmovie.enums.SentenceContext('direction'), 'direction'), (pocketmovie.enums.SentenceContext('actor_name'), 'actor_name')], max_length=20)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeBigramKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(pocketmovie.enums.Genre('action'), 'action'), (pocketmovie.enums.Genre('romance'), 'romance'), (pocketmovie.enums.Genre('horror'), 'horror')], max_length=20)),
                ('gram_1', models.CharField(choices=[(pocketmovie.enums.SentenceType('declarative'), 'declarative'), (pocketmovie.enums.SentenceType('interrogative'), 'interrogative'), (pocketmovie.enums.SentenceType('exclamatory'), 'exclamatory'), (pocketmovie.enums.SentenceType('imperative'), 'imperative')], max_length=20)),
                ('gram_2', models.CharField(choices=[(pocketmovie.enums.SentenceType('declarative'), 'declarative'), (pocketmovie.enums.SentenceType('interrogative'), 'interrogative'), (pocketmovie.enums.SentenceType('exclamatory'), 'exclamatory'), (pocketmovie.enums.SentenceType('imperative'), 'imperative')], max_length=20)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeTrigramKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(pocketmovie.enums.Genre('action'), 'action'), (pocketmovie.enums.Genre('romance'), 'romance'), (pocketmovie.enums.Genre('horror'), 'horror')], max_length=20)),
                ('gram_1', models.CharField(choices=[(pocketmovie.enums.SentenceType('declarative'), 'declarative'), (pocketmovie.enums.SentenceType('interrogative'), 'interrogative'), (pocketmovie.enums.SentenceType('exclamatory'), 'exclamatory'), (pocketmovie.enums.SentenceType('imperative'), 'imperative')], max_length=20)),
                ('gram_2', models.CharField(choices=[(pocketmovie.enums.SentenceType('declarative'), 'declarative'), (pocketmovie.enums.SentenceType('interrogative'), 'interrogative'), (pocketmovie.enums.SentenceType('exclamatory'), 'exclamatory'), (pocketmovie.enums.SentenceType('imperative'), 'imperative')], max_length=20)),
                ('gram_3', models.CharField(choices=[(pocketmovie.enums.SentenceType('declarative'), 'declarative'), (pocketmovie.enums.SentenceType('interrogative'), 'interrogative'), (pocketmovie.enums.SentenceType('exclamatory'), 'exclamatory'), (pocketmovie.enums.SentenceType('imperative'), 'imperative')], max_length=20)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeUnigramKeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(pocketmovie.enums.Genre('action'), 'action'), (pocketmovie.enums.Genre('romance'), 'romance'), (pocketmovie.enums.Genre('horror'), 'horror')], max_length=20)),
                ('gram_1', models.CharField(choices=[(pocketmovie.enums.SentenceType('declarative'), 'declarative'), (pocketmovie.enums.SentenceType('interrogative'), 'interrogative'), (pocketmovie.enums.SentenceType('exclamatory'), 'exclamatory'), (pocketmovie.enums.SentenceType('imperative'), 'imperative')], max_length=20)),
                ('probability', models.FloatField()),
            ],
        ),
    ]
