# Generated by Django 2.2.5 on 2019-10-10 01:48

from django.db import migrations, models
import pocketmovie.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('genre', models.CharField(choices=[(pocketmovie.enums.Genre('action'), 'action'), (pocketmovie.enums.Genre('romance'), 'romance'), (pocketmovie.enums.Genre('horror'), 'horror')], max_length=20)),
                ('sentence_context', models.CharField(choices=[(pocketmovie.enums.SentenceContext('description'), 'description'), (pocketmovie.enums.SentenceContext('dialogue'), 'dialogue'), (pocketmovie.enums.SentenceContext('direction'), 'direction'), (pocketmovie.enums.SentenceContext('actor_name'), 'actor_name')], max_length=20)),
                ('sentence_type', models.CharField(choices=[(pocketmovie.enums.SentenceType('declarative'), 'declarative'), (pocketmovie.enums.SentenceType('interrogative'), 'interrogative'), (pocketmovie.enums.SentenceType('exclamatory'), 'exclamatory'), (pocketmovie.enums.SentenceType('imperative'), 'imperative')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StartSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_context', models.CharField(choices=[(pocketmovie.enums.SentenceContext('description'), 'description'), (pocketmovie.enums.SentenceContext('dialogue'), 'dialogue'), (pocketmovie.enums.SentenceContext('direction'), 'direction'), (pocketmovie.enums.SentenceContext('actor_name'), 'actor_name')], max_length=20)),
                ('sentence_type', models.CharField(choices=[(pocketmovie.enums.SentenceType('declarative'), 'declarative'), (pocketmovie.enums.SentenceType('interrogative'), 'interrogative'), (pocketmovie.enums.SentenceType('exclamatory'), 'exclamatory'), (pocketmovie.enums.SentenceType('imperative'), 'imperative')], max_length=20)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('sentence_context', 'sentence_type')},
            },
        ),
    ]
